console.log("start");
console.log("do I have coffee beans? (no)");
console.log("add coffee beans to shopping list");
console.log("buy coffee beans");
console.log("grind beans");
console.log("is the coffee pot clean? (no)");
console.log("clean the pot");
console.log("add filter to coffee machine");
console.log("add coffee grounds to filter");
console.log("add water to coffee machine");
console.log("start coffee maker");
console.log("wait for coffee to finish brewing");
console.log("end");
